openapi: 3.1.0
info:
  title: Nationgraph Accounts Organization API
  version: 0.2.36
tags:
- name: Organization
paths:
  /api/v3/organizations/{organization_id}/documents:
    post:
      tags:
      - Organization
      summary: Add Documents To Organization
      operationId: add_documents_to_organization_api_v3_organizations__organization_id__documents_post
      security:
      - HTTPBearer: []
      parameters:
      - name: organization_id
        in: path
        required: true
        schema:
          type: string
          title: Organization Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadDocumentRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    get:
      tags:
      - Organization
      summary: Get Organization Documents
      operationId: get_organization_documents_api_v3_organizations__organization_id__documents_get
      security:
      - HTTPBearer: []
      parameters:
      - name: organization_id
        in: path
        required: true
        schema:
          type: string
          title: Organization Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - Organization
      summary: Delete Organization Documents
      operationId: delete_organization_documents_api_v3_organizations__organization_id__documents_delete
      security:
      - HTTPBearer: []
      parameters:
      - name: organization_id
        in: path
        required: true
        schema:
          type: string
          title: Organization Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
              title: Document Ids
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    UploadDocumentRequest:
      properties:
        name:
          type: string
          title: Name
        path:
          type: string
          title: Path
        organization_id:
          type: string
          title: Organization Id
        user_id:
          type: string
          title: User Id
      type: object
      required:
      - name
      - path
      - organization_id
      - user_id
      title: UploadDocumentRequest
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
