openapi: 3.1.0
info:
  title: Nationgraph Accounts User Profile API
  version: 0.2.36
tags:
- name: User Profile
paths:
  /api/v3/user-profiles/{user_id}:
    get:
      tags:
      - User Profile
      summary: Get User Profile
      operationId: get_user_profile_api_v3_user_profiles__user_id__get
      security:
      - HTTPBearer: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
          title: User Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    patch:
      tags:
      - User Profile
      summary: Update User Profile
      description: Update the user's profile settings.
      operationId: update_user_profile_api_v3_user_profiles__user_id__patch
      security:
      - HTTPBearer: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
          title: User Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v3/user-profiles/documents/search:
    post:
      tags:
      - User Profile
      summary: Search User Profile Documents
      operationId: search_user_profile_documents_api_v3_user_profiles_documents_search_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_search_user_profile_documents_api_v3_user_profiles_documents_search_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v3/user-profiles/{user_id}/document-summary:
    post:
      tags:
      - User Profile
      summary: Generate User Document Summary
      operationId: generate_user_document_summary_api_v3_user_profiles__user_id__document_summary_post
      security:
      - HTTPBearer: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
          title: User Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    InstitutionFiltersEnum:
      type: string
      enum:
      - institution_type
      - institution_list
      title: InstitutionFiltersEnum
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    InstitutionTypePayload:
      properties:
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        institution_type:
          anyOf:
          - type: string
          - type: 'null'
          title: Institution Type
        account_types:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Account Types
        states:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: States
        counties:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Counties
        cities:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Cities
        population_min:
          anyOf:
          - type: integer
          - type: 'null'
          title: Population Min
        population_max:
          anyOf:
          - type: integer
          - type: 'null'
          title: Population Max
        search_query:
          anyOf:
          - type: string
          - type: 'null'
          title: Search Query
      type: object
      title: InstitutionTypePayload
    InstitutionListPayload:
      properties:
        institution_ids:
          items:
            type: string
          type: array
          title: Institution Ids
        name:
          type: string
          title: Name
        original_filename:
          anyOf:
          - type: string
          - type: 'null'
          title: Original Filename
        original_filter:
          anyOf:
          - $ref: '#/components/schemas/InstitutionTypePayload'
          - type: 'null'
      type: object
      required:
      - name
      title: InstitutionListPayload
    Body_search_user_profile_documents_api_v3_user_profiles_documents_search_post:
      properties:
        user_id_to_search:
          type: string
          title: User Id To Search
      type: object
      required:
      - user_id_to_search
      title: Body_search_user_profile_documents_api_v3_user_profiles_documents_search_post
    TerritoryVisibility:
      type: string
      enum:
      - private
      - organization
      title: TerritoryVisibility
    UserProfileInstitutionFilter:
      properties:
        id:
          anyOf:
          - type: string
            format: uuid
          - type: 'null'
          title: Id
        visibility:
          $ref: '#/components/schemas/TerritoryVisibility'
          default: private
        type:
          $ref: '#/components/schemas/InstitutionFiltersEnum'
        payload:
          anyOf:
          - $ref: '#/components/schemas/InstitutionTypePayload'
          - $ref: '#/components/schemas/InstitutionListPayload'
          title: Payload
      type: object
      required:
      - type
      - payload
      title: UserProfileInstitutionFilter
    UserProfileRequest:
      properties:
        user_id:
          anyOf:
          - type: string
          - type: 'null'
          title: User Id
        role:
          anyOf:
          - type: string
          - type: 'null'
          title: Role
        document_summary:
          anyOf:
          - type: string
          - type: 'null'
          title: Document Summary
        filters:
          anyOf:
          - items:
              $ref: '#/components/schemas/UserProfileInstitutionFilter'
            type: array
          - type: 'null'
          title: Filters
      type: object
      title: UserProfileRequest
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
